# Generated by Django 3.0.6 on 2020-05-12 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='codigoSensor',
            field=models.CharField(default=1, max_length=20, verbose_name='codigoSensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
