# Generated by Django 3.0.3 on 2020-05-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0002_auto_20200512_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='origen',
            field=models.CharField(default=1, max_length=50, verbose_name='origen'),
            preserve_default=False,
        ),
    ]
